--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: example-ingress
spec: 
  rules: 
    - 
      host: hello-world.info
      http: 
        paths: 
          - 
            backend: 
              serviceName: helloweb
              servicePort: 8080
            path: /*
